project_id = "so-thu-chi"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]

[auth.external.google]
enabled = false
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"

[functions.delete-account]
verify_jwt = true
