import {
  Apple,
  Award,
  Baby,
  Banknote,
  Bed,
  Beer,
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  Camera,
  Car,
  Carrot,
  Cat,
  CircleDollarSign,
  CirclePlus,
  Clapperboard,
  Coffee,
  CupSoda,
  Dog,
  Droplet,
  Dumbbell,
  Ellipsis,
  Flower2,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  HandCoins,
  HandHeart,
  Hammer,
  Heart,
  House,
  Landmark,
  Laptop,
  Leaf,
  Lightbulb,
  Music,
  PartyPopper,
  Pill,
  Pizza,
  PiggyBank,
  Plane,
  Receipt,
  Scissors,
  Shield,
  Shirt,
  ShoppingCart,
  Smartphone,
  Smile,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Tag,
  Train,
  TrendingUp,
  Truck,
  Tv,
  Umbrella,
  Users,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/** Seules icônes autorisées pour les catégories (nom stocké en base → composant). */
export const ICONS: Readonly<Record<string, LucideIcon>> = {
  utensils: Utensils,
  shirt: Shirt,
  cat: Cat,
  'shopping-cart': ShoppingCart,
  coffee: Coffee,
  plane: Plane,
  dumbbell: Dumbbell,
  apple: Apple,
  gift: Gift,
  'gamepad-2': Gamepad2,
  bus: Bus,
  fuel: Fuel,
  home: House,
  zap: Zap,
  droplet: Droplet,
  wifi: Wifi,
  smartphone: Smartphone,
  stethoscope: Stethoscope,
  pill: Pill,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  sparkles: Sparkles,
  'party-popper': PartyPopper,
  clapperboard: Clapperboard,
  baby: Baby,
  users: Users,
  shield: Shield,
  wrench: Wrench,
  sofa: Sofa,
  carrot: Carrot,
  'cup-soda': CupSoda,
  heart: Heart,
  'hand-heart': HandHeart,
  receipt: Receipt,
  ellipsis: Ellipsis,
  'circle-dollar-sign': CircleDollarSign,
  award: Award,
  'trending-up': TrendingUp,
  briefcase: Briefcase,
  'plus-circle': CirclePlus,
  // extras pour les catégories personnalisées
  car: Car,
  bike: Bike,
  train: Train,
  music: Music,
  camera: Camera,
  beer: Beer,
  pizza: Pizza,
  cake: Cake,
  dog: Dog,
  bed: Bed,
  lightbulb: Lightbulb,
  scissors: Scissors,
  laptop: Laptop,
  tv: Tv,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  'hand-coins': HandCoins,
  gem: Gem,
  umbrella: Umbrella,
  hammer: Hammer,
  tag: Tag,
  star: Star,
  'flower-2': Flower2,
  leaf: Leaf,
  truck: Truck,
  'building-2': Building2,
  wallet: Wallet,
  smile: Smile,
};

export const ICON_NAMES: readonly string[] = Object.keys(ICONS);

/** Palette de 16 couleurs du sélecteur (maquette « Sửa danh mục »). */
export const COLOR_PALETTE: readonly string[] = [
  '#F9A825',
  '#26C6DA',
  '#7986CB',
  '#1E88E5',
  '#FF8A65',
  '#7E57C2',
  '#AFB42B',
  '#66BB6A',
  '#EC407A',
  '#FF7043',
  '#42A5F5',
  '#8D6E63',
  '#5C6BC0',
  '#26A69A',
  '#EF5350',
  '#78909C',
];

export function iconFor(name: string): LucideIcon {
  return ICONS[name] ?? Tag;
}
